_target_: src.datamodule.cartoon.CartoonDatamodule
data_dir: ${paths.data_dir}cartoon/
train_ratio: 0.8
val_ratio: 0.1
test_ratio: 0.1
batch_size: 16
num_workers: 0
pin_memory: False
num_samples: null